#!/usr/bin/env bash
# Install the load balancer
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get install haproxy=1.5.\*
