#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and "Hi" 1 times
cont=0
while [ $cont -lt 10 ];
do
    if [ $cont -eq 3 ]
    then
	echo "bad luck"
    elif [ $cont -eq 7 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let cont=cont+1
done
