#!/usr/bin/env bash
#  Bash script that displays the time
hour=0
while [ $hour -le 12 ];
do
    echo "Hour: $hour"
    min=1
    while [ $min -le 59 ];
    do
	echo  $min
	let min=min+1
    done
    let hour=hour+1
done
